# client/Dockerfile

FROM node:18 AS build

WORKDIR /app

COPY client/package*.json ./
COPY client/ ./

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
