version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://finance-app-user:bjkwjewg0'13£!Abc@127.0.0.1:27017/finance-app?authSource=finance-app
    network_mode: "host"
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
